# Generated by Django 2.1.5 on 2019-02-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unicorn',
            new_name='TestApp',
        ),
    ]
